[package]
name = "proforge"
version = "0.1.0"
edition = "2021"

description = "WIP, a CLI inspired by cookiecutter and projen for creating new projects"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
